// <auto-generated />
using System;
using SignerApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace SignerApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210416183719_SystemFilename")]
    partial class SystemFilename
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("SignerApi.Models.ApiActivity", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CertHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientIPAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<string>("Operation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .HasColumnType("TEXT");

                    b.Property<string>("SystemFilename")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("UniqueFilenameKey")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("ApiActivity");
                });
#pragma warning restore 612, 618
        }
    }
}
